name: 'üè∑Ô∏è Auto-Label PRs'
on:
  - pull_request_target

jobs:
  label:
    name: 'Add labels'
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write # to update the pull request with labels
      issues: write # to create labels if they don't exist

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # ratchet:actions/labeler@v6.0.1
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
