name: Add Labels to PRs
on:
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # to update the pull request with labels
      issues: write # to create labels if they don't exist

    steps:
      - uses: actions/labeler@v6.0.1
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
