name: 'ðŸ’¥ Merge Conflicts'
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    name: 'Label PRs with merge conflicts'
    runs-on: ubuntu-slim
    permissions: write-all
    steps:
      - name: Check for merge conflicts
        uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0 # ratchet:eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: 'ðŸ’¥ Merge Conflicts'
          removeOnDirtyLabel: 'PR: ready to ship'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
